# GET http://localhost:8080/login?user_name=qingh&user_password=123456

POST http://localhost:9998/api/v1/login
content-type: application/json

{
	"user":"qingh",
	"age2":"30",
	"age":30
}


# content-type: application/x-www-form-urlencoded
# user_name=blue&user_password=123456

# 
# {
# 	"user_name":"blue",
# 	"user_password":"123456"
# }